### ISSUE TITLE
Background picture fades out to white

### ISSUE THREAD

**Issue by ProtoIxa** [KaminariKillua/Themes#10]
Logged in today and saw the assets load up, the background picture loads and quickly fades to pure white as shown here: https://imgur.com/Wlbraoe , as you can see, the layout, direct messaging background pic, and (cant see) the per person profile background pic are all working. So the only thing thats broken is the main background fades to white. do you know why?

**Comment by KaminariKillua** [comment]
Heya, this is because discord changed the background again so it's like that for everyone. There are temp fixes available in the betterdiscord2 server. I don't have much time to update my themes ATM but will do so when I get the chance.
xx
