### ISSUE TITLE
Side Panel Grey and cant be changed 

### ISSUE THREAD

**Issue by Stellarchain** [KaminariKillua/Themes#12]
Hello,
i have been seeing the grey side panel of where the members are and i cant seem to fix it
Could you please fix this, also there will be an image/screenshot of the problem so you know what i am looking at

Thank you for reading this message
Stellar
![jmebqqp](https://user-images.githubusercontent.com/33031654/38355253-a46c67bc-38bc-11e8-9fed-f5a01ac5734f.png)

**Comment by dragonzair** [comment]
I was just coming to ask about this! It seems the members list isn't showing the theme at all- I'm using the Glacial Theme for reference.

I'm kind of relieved I'm not the only one, as I thought it was my own problem. Hope this gets resolved :)

**Comment by KaminariKillua** [comment]
Hello, this is due to a discord update. I'll resolve this shortly together with some other patches.

**Comment by dragonzair** [comment]
Thank you so much for the quick response! :)

**Comment by KaminariKillua** [comment]
No problem! The next version will likely be out tomorrow.

**Comment by KaminariKillua** [comment]
Fixed in the latest update.
xx
