### ISSUE TITLE
Another New Update Another patch needed

### ISSUE THREAD

**Issue by Stellarchain** [KaminariKillua/Themes#13]
Hello again!

There has been the grey colored channel selections while i had it red
if you dont know what i am talking about, it will make more sense to see the screenshot
![zldd9et](https://user-images.githubusercontent.com/33031654/39396693-55a63cc2-4af3-11e8-890b-8db43e2b5179.png)
Thank you 
~Stellar

**Comment by KaminariKillua** [comment]
Hi, it was worse than this so I just did this as temp fix, real fix in like a week idk when I have time xx

**Comment by KaminariKillua** [comment]
A better semi-fix has been rolled out thanks to intrnl. xx

**Comment by KaminariKillua** [comment]
Updated, please downloaded the latest version.
xx
