### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Ninetales420** [KaminariKillua/Themes#15]
As much as the Prison themes, I've been noticing that discord has 30-40% usage with them activated on my PC with a high end 4th gen i5
![image](https://user-images.githubusercontent.com/24677730/39449656-eb76fbf2-4cc8-11e8-9f3b-a91e04d00b7e.png)
I have no plugins or other themes activated

**Comment by KaminariKillua** [comment]
I'm aware of this issue, however it's probably due to the many transition animations I have in there and it'll probably take a case rewrite to fix it. I was planning it in the summer, so approx 2-3 months. xx

**Comment by KaminariKillua** [comment]
For stylish purposes, I've decided to leave the animations in. I have however, removed a lot of unnecessary animations, so you should see a slight improvement.
xx
