### ISSUE TITLE
Profile status display problem

### ISSUE THREAD

**Issue by NursuryRhyme** [KaminariKillua/Themes#18]
Recently ive been getting this bug where the person's status colour covers 90% of the persons profile when I click on their names like this:
![image](https://user-images.githubusercontent.com/32021152/42175807-c8d70620-7df4-11e8-81d4-32db0ebb0265.png)
how do i fix this?

**Comment by KaminariKillua** [comment]
Hello this is a known issue but I currently don't have time to fix it, will perform a big overhaul on my theme during summer vacation. Please hold out until then or adjust it manually using the help of the betterdiscord server.
xx

**Comment by KaminariKillua** [comment]
Updated, please download the latest version.
xx
