### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by Stellarchain** [KaminariKillua/Themes#19]
There are 4 new issues with the theme.

1. The gaming tab isnt customized.
2. Clicking and viewing someones profile will view the Status circle.
3. Viewing someones profile and hovering close to the circle will make the status circle bigger.
4. The DM picture is gone.

![h6n8ot2](https://user-images.githubusercontent.com/33031654/43038547-55727828-8d1b-11e8-88ed-1f7802e7ca84.png)
![emkz6ow](https://user-images.githubusercontent.com/33031654/43038548-55876620-8d1b-11e8-9c1f-781b7395e9cf.png)
![shpr4to](https://user-images.githubusercontent.com/33031654/43038549-5a8befba-8d1b-11e8-97ae-2c8afb5f3edf.png)
![b590b4a](https://user-images.githubusercontent.com/33031654/43038553-7c4f85ee-8d1b-11e8-8a7c-93579758ee4d.gif)

**Comment by KaminariKillua** [comment]
Hello I am aware of all these already but thanks for reporting
xx

**Comment by aksisz** [comment]
hello @KaminariKillua , i have the same exact problems , and servers channels and server list also aren't customized (i have this problem with both glacial prison and infernal prison)
![2018-08-04 10](https://user-images.githubusercontent.com/42095263/43678043-819feeb6-980c-11e8-8d7f-a4e70bec1d78.png)
![2018-08-04 9](https://user-images.githubusercontent.com/42095263/43678046-8ac629a6-980c-11e8-9d34-0e99a73ba111.png)

**Comment by KaminariKillua** [comment]
I noticed this too, this started like 2 days ago. The discord updates are now really impacting the visuals, I will try to hotfix next week inbteween work.
xx

**Comment by aksisz** [comment]
alos this
![2018-08-05 1](https://user-images.githubusercontent.com/42095263/43689549-8d4a76aa-98fc-11e8-921a-45a7092afe34.png)

**Comment by KaminariKillua** [comment]
Updated, please download the latest version.
xx
