### ISSUE TITLE
New Issue After discord update

### ISSUE THREAD

**Issue by Roboman01851** [KaminariKillua/Themes#21]
when i updated discord, the theme i was using broke (sakura prison). only the left side bar were all the channels are is propperly textured and the users name and message seem to overlap eachother.
![discord_2018-08-10_18-30-20](https://user-images.githubusercontent.com/28986092/43983953-72773bce-9ccb-11e8-8832-329d325ef6fb.png)

**Comment by aksisz** [comment]
me too

**Comment by aksisz** [comment]
but i had it before the update

**Comment by natsumatsuri** [comment]
update please

**Comment by KaminariKillua** [comment]
Updated, please download the latest version.
xx
