### ISSUE TITLE
glacial prison and sakura's prison just suddenly stopped working while i was using dicord, right in front of me

### ISSUE THREAD

**Issue by jack652** [KaminariKillua/Themes#23]
the glacial prison and sakura's prison just suddenly stopped working while i was using dicord, right in front of me, as well as another theme created by someone else.
oh and the place at top left where is supposezd to be a sphre with the discord logo diapeared, wich makes me unable to acess my dms, but it came back shortely after
![#📷screenshots - Discord 08-03-19 20_26_39](https://user-images.githubusercontent.com/48365199/54050815-769d2280-41e0-11e9-9773-866d5268eb0a.png)

**Comment by KaminariKillua** [comment]
Heya, the images are currently not working due to issues with the host (puush). You can check their twitter for updates. They should reappear once this has been solved.
xx
