### ISSUE TITLE
unable to open user settings 

### ISSUE THREAD

**Issue by xharas** [KaminariKillua/Themes#4]
this is on one of the bd exclusive settings, found in core-i'm not too sure what its called as i'm unable to check now that i can't open user settings but it was one of the choices in core(?)

**the user settings button can't be clicked**

http://i.imgur.com/oxMLU9A.png
http://i.imgur.com/j6Iae1a.png
http://i.imgur.com/OhPoeQN.png

and if you're wondering, yes i have tried opening settings before bd has loaded but the bd settings didn't show up when bd did load, etc, etc! 
i really don't mind this atm but it would be appreciated if this could be fixed!!

-
-
-

before i turned on this bd exclusive setting found in core i noticed that if i ran my cursor over the words "voice channels" after running over there was two copies of "voice channels" overlapping each other

-
-
-

_don't mind this last request:_
this is 100% completely personal preference but i think emotes are just a bit too big?! 

http://i.imgur.com/mJZWdU4.png
http://i.imgur.com/wWWi8Vi.png
http://i.imgur.com/hfKCCkS.png

in time i will get used to the size tho so its whatever but maybe add that we can choose the emote size? or something like a choice between two sizes?

**Comment by KaminariKillua** [comment]
Hey there, sorry to get to you this late, I've just noticed that my github mails get auto-filtered into the trash. Are you still suffering from this? Also, thanks for the emoji feedback - The next time Discord does a major update, I'll be sure to include the variable to change it in the theme. For now, you can use BetterDiscord's built-in css feature to change this. Simply change the pixels in this and paste it in your CSS box.
`.emoji, .icon-3XfMwL{
    width: 50px !important;
    height: 50px !important;
} `

**Comment by xharas** [comment]
no worries, ive actually just used ctrl+, and opened settings and fixed that part and thanks for the emoji css
