### ISSUE TITLE
Channel titles overlapping channels

### ISSUE THREAD

**Issue by ProtoIxa** [KaminariKillua/Themes#6]
![image](https://user-images.githubusercontent.com/32021152/30514741-25061dc2-9ae9-11e7-99a0-130a5c182f93.png)
as you can see ehre the channel text titles are overlapping the channel buttons. It doesnt prevent me from clicking them so its not a big deal but its visually annoying

**Comment by ProtoIxa** [comment]
Im using your glacial prison base with changed pictures only

**Comment by KaminariKillua** [comment]
Hello Proto, I was away for the weekend and I've just noticed this as well. It seems like discord applied a small update to the channel list, I will fix this after my dinner. xx

**Comment by KaminariKillua** [comment]
Fixed. xx
