### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by notcarksss** [KaminariKillua/Themes#8]
The colors for this theme work perfectly fine, but it says loading assets etc and the background image doesn't show. If you could help with this, it would be much appreciated
![image](https://user-images.githubusercontent.com/16636304/32082247-33ea6dd2-bab2-11e7-98f5-bda65f343600.png)

**Comment by KaminariKillua** [comment]
Are you using the Dark Theme? It only works well with Light on.

**Comment by ProtoIxa** [comment]
Im having the same issue and my light mode is already on, this started happening just today

**Comment by KaminariKillua** [comment]
Strange it's not happening for me. It could be you're using the Renamer or Quoter plugin, which currently break BD I believe. I already removed mine from my plugins folder and it works fine now.

**Comment by ProtoIxa** [comment]
my plugins folder is empty

**Comment by KaminariKillua** [comment]
I've just started discord and I have the same issue, I'll look into it

**Comment by razorethan** [comment]
Yea Same problem here.

**Comment by KaminariKillua** [comment]
Currently fixing it, fix out later today

**Comment by notcarksss** [comment]
Thank you KaminariKillua, never had this until recently so either Discord updated or BetterDiscord is slightly broken. Ive never known this to happen before so I have no idea what happened.

**Comment by notcarksss** [comment]
Please comment here when you have fixed the issue, and thanks again :)

**Comment by KaminariKillua** [comment]
V7.0 has now been released, please download the new version from the repo :)

**Comment by notcarksss** [comment]
Ty
