### ISSUE TITLE
Theme broken for 6.1 update?

### ISSUE THREAD

**Issue by NicheAshriver** [KaminariKillua/Themes#9]
I contacted support on the BetterDiscord server and they gave me a Transparency Fix thing to put in my custom CSS thing. It did not fix the problem. I cant see the background but all the color changes and stuff still show up. But when I downloaded a different theme it worked with that one. BetterDiscord told me to contact the person who created the theme to let them know it needs to be fixed. I'm sorry but I'm a newbie when it comes to this so if you have questions please let me know. ^^

I'm trying to use Glacial Prison. I can provide the code for the transparency fix they gave me if you need it... umm... anything else you need please just ask and I will do my best to help. ^^

**Comment by KaminariKillua** [comment]
Hello, currently working on a fix for this - please look at the UI Error issue for further updates.

**Comment by NicheAshriver** [comment]
oh oki. Thank you. ^^
